org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.nonTransitiveRClass=true
# Proje AndroidX kullanmiyor (yalniz Android'in kendi siniflari)
android.useAndroidX=false
# Klasor yolunda Turkce karakter/bosluk olursa (orn. C:\Users\Yusuf\Masaüstü) Windows'ta
# derleme durmasin
android.overridePathCheck=true
